### ISSUE TITLE
The Go Daddy scholarship link is broken

### ISSUE THREAD

**Issue by shubheksha** [Ladies-Storm-Hackathons/GHC-Scholarships#13]
It looks like the page was moved & now it leads to a 404.

**Comment by blossomica** [comment]
@shubheksha - Great catch! I believe that is because the deadline for it has passed. It was listed as a job posting on Jobvite platform, I think it is more of the posting being deleted than it being moved. If you happen to find a working URL of it anywhere please post it here, however it is broken in all sites it was announced at, so I feel that this is more of the link not existing anymore. I am not sure of what is the right fix for that, hopefully someone else will chime in on that.
