### ISSUE TITLE
NetApp entry:  incorrect student status

### ISSUE THREAD

**Issue by netapp-nelc** [Ladies-Storm-Hackathons/GHC-Scholarships#96]
Hi!

Thanks for all you do.

The only thing wrong with the NetApp entry is that it says “undergrad”. All degree seeking students at a 4 year college or university can apply.

Thanks!
--nelc

**Comment by KM5538** [comment]
Does this mean students pursuing masters degree (2 yr program) can apply?

**Comment by blossomica** [comment]
@netapp-nelc  - The wording in NetApp's application is confusing. So if it can be edited in the opportunity that would clear some confusion. Most people mean undergrad when they say 4 year college/university, except if NetApp is implying studying at a college/university that grants 4 year degrees even if one is not registered to a 4 year program. Making it clear in NetApp's post will help avoid some people not applying due to misunderstandings. 

@KM5538  - Yes, they can. Here's the source: https://twitter.com/sindhugudivada/status/1151908243666456576

It looks like it is also open to people pursuing these types of degrees, full time: 

Undergrad
Masters
PhD
MBA
JD
Associates

**Comment by aceyoung9** [comment]
Fixed! Thanks, @netapp-nelc @blossomica !
